### ISSUE TITLE
Where can I find the description about the adreno’s counters?

### ISSUE THREAD

**Issue by HackHarry** [google/hardware-perfcounter#1]
I want to collect performance datas which are the same as SnapDragon profiler. But I can't find any information about the counters which this project collects at Qcom Websites, and the counters are different from Snapdragon profiler.

Could you give me some suggestions? Thanks a lot.

**Comment by antiagainst** [comment]
Right there aren't much information about Adreno perf counters readily available from QC. What I have here in the repo is from reading QC kernel source code (see my blog post [here](https://www.lei.chat/posts/sampling-performance-counters-from-gpu-drivers/)) and Mesa open source drivers for it. I summarized some resources at the end of [this](https://www.lei.chat/posts/android-linux-gpu-drivers-internals-and-resources/#driver-resources) blog post. Helpfully that helps.

The purpose of this project is actually to collect and aggregate such information in a minimal and cross-vendor C library so one can feel free to link into the normal app to show performance numbers without resorting to heavy vendor-specific GPU tools. Curious what's your needs here? Does what's provided in this repo satisfying it? It's half backed for sure for now; but right now it has all the low-level counters exposed for both Adreno and Mali. Just need to build up the cross-vendor upper layer. I'm hoping to push it further later if I have more free time. Let me know. :)

**Comment by HackHarry** [comment]
Thanks for your reply!

I want to collect mobile GPU performance data, which can help us locate performance problems. I have finished collecting Mali with HWCPipe and PVR GPU's counters with PVR SDK, only Adreno GPU is left. I try to decomplie Snapdragon profiler, and find the same counters as yours. But it's difficult for me to find the formula between counters and performance data in decompiled code.

I would like to know how to calculate the performance data displayed by Snapdragon profiler with low-level counters.

**Comment by antiagainst** [comment]
Yeah, I see what you are trying to do there. But unfortunately it's also something TODO for me so I don't have the it readily available..

**Comment by riceliu** [comment]
mark. I also have plan to do it.

**Comment by Holy-YxY** [comment]
Hi, everyone. I have the same questions and requirements. I know [mesa](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/freedreno/ds/fd_pps_driver.cc) are some formulas for calculating indicators, but I haven't fully verified their accuracy at present.I hope this problem can be opened continuously, and you can continue to collect and supplement it together.

**Comment by HackHarry** [comment]
> Hi, everyone. I have the same questions and requirements. I know [mesa](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/freedreno/ds/fd_pps_driver.cc) are some formulas for calculating indicators, but I haven't fully verified their accuracy at present.I hope this problem can be opened continuously, and you can continue to collect and supplement it together.

It's great!

I try to decompile _Snapdragon Profiler_ and get some key about A6XX counter. My results is basically the same as mesa's, but something is different.
1. The `Instructions` values in mesa is 4 times smaller than mine, and my test result shows I am right.
2. The mesa calculates `Fragment Shader` with `4 * HLSQ_QUADS`, but I try to collect `A6XX_HLSQ_QUADS` and find it's always 0. I try to use `A6XX_HLSQ_PIXELS` instead and it works for my case. (Maybe `HLSQ_QUADS` works for A5XX or other)

Besides, it seems to face the same problems as me. For example, I can't get formula about `Read Total`, `Write Total`, which is diffcult to get by static analysis, but these counters are important for me.

**Comment by HackHarry** [comment]
There are several counters, which is calculated by `max_freq` in _mesa_. So I read the source of _mesa_, trying to find how it gets max_freq. Unfortunately, I found that there is no way to get the value of `max_freq`.

mesa use _[mesa-drm](https://github.com/freedesktop/mesa-drm)_ to communication with gpu driver. And in _mesa-drm_, there are two functions about `max_freq`.
1. one is [kgsl_pipe](https://github.com/freedesktop/mesa-drm/blob/6d821612d9a4bc4f61d64040a1852a4f139bd28a/freedreno/kgsl/kgsl_pipe.c#L49), which return -1 default.
2. one is [msm_pipe](https://github.com/freedesktop/mesa-drm/blob/6d821612d9a4bc4f61d64040a1852a4f139bd28a/freedreno/msm/msm_pipe.c#L66). I tried it in Pixel 4a but got 0.

Now, I focu on _[agi](https://github.com/google/agi)_, and find it uses `libgpudataproducer.so` to get counter. `libgpudataproducer.so` seems to be a gpu driver, and I have no idea about it.

This is all my progress so far。

**Comment by riceliu** [comment]
> 

@HackHarry I use one rooted phone (Mi 8) and try to hook the ioctl systemcall while runing perfdog/snapdragon profiler.
It seems that's work for me to find which counter they are using：
for example，Write Total (GPU Memory Stats) should be group = 13 and counter id = 84; Read Total (GPU Memory Stats) should be group = 13 and counter id = 63;

I will try to test it. 

Following is my wechat code. As it seems not so convenient to do discuss on github so anyone interested can contact me  and I would prefer to do more discuss on online group.
![image](https://user-images.githubusercontent.com/5362719/178427840-f4544350-9acd-416c-9f5a-5a43fd58c6de.png)
